class Cell{
    constructor(i_,j_){
        this.i=i_;
        this.j=j_;
        this.size=40;
        this.x=this.j*this.size;
        this.y=this.i*this.size;
        this.obstacle=false;
        this.g=0;
        this.h=0;
        this.f=0;
        this.parent=null;
    }
    show(){
        if(this.obstacle){
            stroke(0);
            fill(0);
            strokeWeight(1);
            rect(this.x,this.y,this.size,this.size);
        }
        else{
            stroke(0);
            noFill();
            strokeWeight(1);
            rect(this.x,this.y,this.size,this.size);
        }
    }
    setObstacle(){
        this.obstacle=true;
    }
}